export interface AuditFinding {
  severity: string;
  title: string;
  description: string;
  recommendation?: string;
}

export interface AuditResult {
  title: string;
  overall_score: string;
  summary: string;
  findings: AuditFinding[];
  timestamp: string;
}

function severityClass(sev: string): string {
  return sev.toUpperCase().replace(/\s+/g, '-');
}

function scoreColor(score: string): string {
  const s = score.toUpperCase();
  if (['CRITICAL', 'POOR'].includes(s)) return '#ef4444';
  if (['HIGH', 'FAIR'].includes(s)) return '#f59e0b';
  if (['MEDIUM', 'GOOD'].includes(s)) return '#3b82f6';
  return '#6b7280';
}

export function generateAuditReport(result: AuditResult): string {
  const timestamp = new Date(result.timestamp).toLocaleString();
  const scoreColorVal = scoreColor(result.overall_score);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(result.title)} - Ency Solutions</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0a; color: #e5e5e5; line-height: 1.6; }
    .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
    .header { text-align: center; padding: 40px 0; border-bottom: 2px solid #1a1a1a; margin-bottom: 40px; }
    .brand { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .brand strong { color: #e5e5e5; }
    h1 { font-size: 28px; margin-bottom: 12px; }
    .timestamp { color: #6b7280; font-size: 13px; }
    .score-section { text-align: center; margin: 32px 0; }
    .score-label { font-size: 14px; color: #9ca3af; margin-bottom: 8px; }
    .score-value { font-size: 48px; font-weight: 800; color: ${scoreColorVal}; letter-spacing: 2px; }
    .summary { background: #111; padding: 24px; border-radius: 12px; margin: 32px 0; border: 1px solid #1a1a1a; }
    .summary h2 { font-size: 18px; margin-bottom: 12px; }
    .findings { margin: 32px 0; }
    .findings h2 { font-size: 18px; margin-bottom: 16px; }
    .finding { padding: 20px; margin-bottom: 16px; border-radius: 8px; border-left: 4px solid; }
    .finding.CRITICAL { background: rgba(239,68,68,0.1); border-color: #ef4444; }
    .finding.HIGH { background: rgba(245,158,11,0.1); border-color: #f59e0b; }
    .finding.MEDIUM { background: rgba(59,130,246,0.1); border-color: #3b82f6; }
    .finding.LOW, .finding.INFO { background: rgba(107,114,128,0.1); border-color: #6b7280; }
    .finding-header { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .severity-badge { padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }
    .finding.CRITICAL .severity-badge { background: #ef4444; color: white; }
    .finding.HIGH .severity-badge { background: #f59e0b; color: black; }
    .finding.MEDIUM .severity-badge { background: #3b82f6; color: white; }
    .finding.LOW .severity-badge, .finding.INFO .severity-badge { background: #374151; color: #9ca3af; }
    .finding-title { font-weight: 600; font-size: 15px; }
    .recommendation { margin-top: 12px; padding: 12px; background: rgba(255,255,255,0.03); border-radius: 6px; font-size: 14px; }
    .footer { text-align: center; padding: 32px 0; margin-top: 40px; border-top: 1px solid #1a1a1a; color: #6b7280; font-size: 13px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <p class="brand">Generated by <strong>Ency Audit Toolkit</strong></p>
      <h1>${escapeHtml(result.title)}</h1>
      <p class="timestamp">Report generated: ${escapeHtml(timestamp)}</p>
    </div>

    <div class="score-section">
      <p class="score-label">Overall Assessment</p>
      <p class="score-value">${escapeHtml(result.overall_score)}</p>
    </div>

    <div class="summary">
      <h2>Summary</h2>
      <p>${escapeHtml(result.summary)}</p>
    </div>

    <div class="findings">
      <h2>Findings (${result.findings.length})</h2>
      ${result.findings
        .map(
          (f) => `
        <div class="finding ${severityClass(f.severity)}">
          <div class="finding-header">
            <span class="severity-badge">${escapeHtml(f.severity)}</span>
            <span class="finding-title">${escapeHtml(f.title)}</span>
          </div>
          <p>${escapeHtml(f.description)}</p>
          ${
            f.recommendation
              ? `<div class="recommendation"><strong>Recommendation:</strong> ${escapeHtml(f.recommendation)}</div>`
              : ''
          }
        </div>
      `
        )
        .join('')}
    </div>

    <div class="footer">
      <p>Ency Solutions — Professional IT Security Auditing</p>
      <p>This report was generated for informational purposes. Contact Ency Solutions for remediation guidance.</p>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
